name: diariopoo
description: Projeto diario de POO
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  time: ^1.3.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

